debug: true
tagFormat: ${version}
verifyConditions: "@semantic-release/github"
analyzeCommits: "@semantic-release/commit-analyzer"
generateNotes: "@semantic-release/release-notes-generator"
prepare:
  - path: '@semantic-release/exec'
    cmd: 'export version=${nextRelease.version}'
  - path: '@semantic-release/exec'
    cmd: 'make files'
  - path: '@semantic-release/exec'
    cmd: 'cat langs.go'

publish:
  - path: "@semantic-release/github"
    assets:
      - path: 'bin/darwin/aoc'
        name: 'aoc-${nextRelease.version}-darwin-amd64'
        label: 'aoc-darwin'
      - path: 'bin/debian/aoc'
        name: 'aoc-${nextRelease.version}-debian-amd64'
        label: 'aoc-debian'
      - path: 'bin/windows/aoc.exe'
        name: 'aoc-${nextRelease.version}-windows-exe'
        label: 'aoc-windows-exe'

success: false
fail: false
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"