debug: true
tagFormat: ${version}
verifyConditions: "@semantic-release/github"
analyzeCommits: "@semantic-release/commit-analyzer"
generateNotes: "@semantic-release/release-notes-generator"
publish: "@semantic-release/github"
success: false
fail: false
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"