debug: true
tagFormat: ${version}
verifyConditions: "@semantic-release/github"
analyzeCommits: "@semantic-release/commit-analyzer"
generateNotes: "@semantic-release/release-notes-generator"
verifyRelease:
  - path: '@semantic-release/exec'
    cmd: 'echo ${nextRelease.version} > .version'
publish:
  - path: "@semantic-release/github"
    assets:
      - path: 'bin/darwin/aoc-darwin-amd64'
        name: 'aoc-${nextRelease.version}-darwin-amd64'
        label: 'aoc-darwin'
      - path: 'bin/debian/aoc-darwin-amd64'
        name: 'aoc-${nextRelease.version}-debian-amd64'
        label: 'aoc-debian'
      - path: 'bin/windows/aoc.exe'
        name: 'aoc-${nextRelease.version}-windows-exe'
        label: 'aoc-windows-exe'

success: false
fail: false
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"