name: Advent of Code Boilerplate Release

on:
  push:
    branches: [ "main" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set next version
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Build Binaries
        run: make binaries
      - name: Release next version
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}