name: Advent of Code Boilerplate PR Build/Test

on: pull_request

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Binaries
        run: make binaries